apiVersion: v1
kind: Service
metada:
  name: jenkins
  labels:
    name: jenkins
    app: jenkins-service
  namespace: inspect-code-tools
spec:
  selector:
    name: jenkins
    app: jenkins-service
  type: NodePort  
  ports:
    - port: 8080
      targetPort: 8080
      nodePort: 32000
      name: jenkins-service