apiVersion: v1
kind: Service
metada:
  name: postgres
  labels:
    name: postgres
    app: postgres-service
  namespace: inspect-code-tools
spec:
  type: ClusterIP
  selector:
    name: postgres
    app: postgres-service
  ports:
    - port: 5432
      name: postgres-service