apiVersion: v1
kind: Service
metada:
  name: sonarqube
  labels:
    name: sonarqube
    app: sonarqube-service
  namespace: inspect-code-tools
spec:
  type: NodePort
  selector:
    name: sonarqube
    app: sonarqube-service
  ports:
    - port: 9000
      targetPort: 9000
      name: sonarqube-service